name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-serial:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build-Serial
      run: cmake -DBACKEND=serial -DCOMPILER=gnu -B build_serial_gnu -S . && make -C build_serial_gnu
    - name: Test-Serial
      run: make test -C build_serial_gnu
  build-and-run-omp:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build-OMP
      run: 
        cmake -DBACKEND=openmp -DCOMPILER=gnu -B build_omp_gnu -S . && make -C build_omp_gnu
    - name: Test-OMP
      run: make test -C build_omp_gnu